### ISSUE TITLE
Is there a way to tell if a queue is empty?

### ISSUE THREAD

**Issue by kevanslumin** [go-stomp/stomp#123]
I want to read all of the messages off of a queue, is there a way to tell how many are in the queue so I know when to stop?

Thanks

**Comment by worg** [comment]
No, see the [specification](http://stomp.github.io/stomp-specification-1.2.html)
Also, take into account that STOMP is a messaging protocol, therefore is inherently impossible to know beforehand how many messages are in a queue, since messages can still be sent to that queue while you're receiving from it.
