### ISSUE TITLE
Add stomp.Dial timeout

### ISSUE THREAD

**Issue by agastalver** [go-stomp/stomp#87]
STOMP client gets stuck (waiting for connectivity) when dialing if the server is not available.

This happens due to the usage of `net.Dial` default `Dialer`:
https://github.com/go-stomp/stomp/blob/a96d395162dc6620eb40f2ca596c3968e3cc1a49/conn.go#L50

There are different options:

- Use a `Dialer`: https://golang.org/src/net/dial.go?s=10748:10808#L337
- Use the `DialTimeout` function: https://golang.org/src/net/dial.go?s=10345:10423#L322

A better approach should use `context` to manage this issue: https://golang.org/src/net/dial.go?s=11711:11799#L359

**Comment by worg** [comment]
You can already use `net.DialTimeout` you just need to use the [`Connect`](https://godoc.org/github.com/go-stomp/stomp#ex-Connect) method instead of Dial.On Nov 12, 2020 07:47, Adolfo Gastalver Rubio <notifications@github.com> wrote:
STOMP client gets stuck (waiting for connectivity) when dialing if the server is not available.
This happens due to the usage of net.Dial default Dialer:
https://github.com/go-stomp/stomp/blob/a96d395162dc6620eb40f2ca596c3968e3cc1a49/conn.go#L50
There are different options:
Use a Dialer: https://golang.org/src/net/dial.go?s=10748:10808#L337Use the DialTimeout function: https://golang.org/src/net/dial.go?s=10345:10423#L322
A better approach should use context to manage this issue: https://golang.org/src/net/dial.go?s=11711:11799#L359

**Comment by agastalver** [comment]
Perfect, then the functionality is already taken into account, thank you!
